### ISSUE TITLE
Trying to get it run ... 

### ISSUE THREAD

**Issue by labskaus** [device42/puppet_to_device42_sync_py#5]
At the moment, I am trying to get this thing running and facing some issues:

Have to run it with Python3, because with Python2 the foreman.client does not run. At the moment I stuck here:

# python3 foremanexplore.py -d
Traceback (most recent call last):
  File "foremanexplore.py", line 212, in <module>
    retval = main()
  File "foremanexplore.py", line 148, in main
    if facts.has_key('is_virtual'):
AttributeError: 'dict' object has no attribute 'has_key'

Does any one have this running on an CentOS 7 or higher?

**Comment by cscaglioned42** [comment]
Hi @labskaus,

Here is a fork with some work that was done to update the script to Python 3:
https://github.com/RomanNyschuk/puppet_to_device42_sync_py
